Working
apostrophecms/asset-es5 pull request #1
Opened 2022-08-01 19:53 UTC by boutell

## Summary

Initial PR

## What are the specific steps to test this change?

Link both this module and the pro-2932 branch of apostrophe into a3-boilerplate and activate this module. `npm run dev` should do an IE11 backwards compatibility build in addition to the regular build (you'll see it in the console output, and page source will show two script tags logged out, one for -modules, one for -nomodules).

Without this module, but with pro-2932 of apostrophe, you should not get an IE11 build, not even with es5: true set for the asset module (you'll get a warning instead).

This module also comes with a simple unit test verifying that an es5 build takes place. I'm intentionally not attempting to port the full power of our old tests for this module which supports a legacy case only. A basic test should be sufficient.

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [X] New feature
- [ ] Refactor
- [X] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2022-08-01 19:55 UTC, boutell commented on index.js
> +            import "${require.resolve('core-js/stable')}";
The `require.resolve` trick allows us to import these relative to this module's dependencies, and will also find them higher up if they were hoisted.

2022-08-02 08:21 UTC, myovchev requested changes

2022-08-02 08:21 UTC, myovchev commented on test/test.js
> +  fs.rmSync(`${__dirname}/public/apos-frontend`, {
`fs.rm` was added in node v14.14.0 so this fails v12x tests.

2022-08-02 08:23 UTC, myovchev commented on package.json
> +    "apostrophe": "apostrophecms/apostrophe#pro-2932",
Just a note, set the appropriate version on release.

2022-08-02 11:58 UTC, myovchev approved these changes

2022-08-02 12:20 UTC, merged